version: '3.9'
services:
  mu-app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: mu-app
    container_name: mu-app
    environment:
      - PORT=3001
    restart: always
    networks:
      - mu-wastewater-infra_default

networks:
  mu-wastewater-infra_default:
    external: true